name: html5-validator

on:
  push:
    branches:
      - master
      - develop
    paths:
      - "**.html"
      - "**.njk"
      - .github/workflows/html5-validator.yml

jobs:
  html5-validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.log
      - name: html5-validator
        uses: Cyb3r-Jak3/html5validator-action@v0.6
        with:
          root: app/views/
          log_file: test_config
          log: DEBUG
