name: stylelint

on: [push]

jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-hub/stylelint@master
        env:
          PATTERN: "src/scss/**/*.scss"
          INDENT_SPACES: "2"
          CONFIG_PATH: ".stylelintrc"
